### ISSUE TITLE
EVNNPC: lỗi không xác định

### ISSUE THREAD

**Issue by thien105080** [trvqhuy/nestup_evn#1]
![image](https://user-images.githubusercontent.com/79859811/190187353-1ca453f7-eaad-4168-8a8d-3a8835be3588.png)
em cảm ơn!

**Comment by trvqhuy** [comment]
cho em hỏi bác có từng login vào web hoặc app của EVN để theo dõi dữ liệu ngày đối với mã KH này chưa ạ?

**Comment by thien105080** [comment]
Chưa a ơi để em thử

**Comment by thien105080** [comment]
Được rồi a nhé, em cảm ơn
