### ISSUE TITLE
[EVNNPC] Unavailable sensors

### ISSUE THREAD

**Issue by caohuongls** [trvqhuy/nestup_evn#10]
**Mô tả lỗi / Describe the bug**
Các sensor unavailable 

**Logs**
Unable to fetch data from EVN Server while requesting new data: Expecting value: line 1 column 1 (char 0)

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.

**Server (thông tin máy chủ đang chạy HA):**
 - OS: Raspberry pi 3 HAOS
 - HA platform: Core
 - HA Version: 2022.10.2

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation : HACS

**Comment by trvqhuy** [comment]
@caohuongls bạn cho mình biết chi nhánh EVN khu vực của bạn nhé

**Comment by caohuongls** [comment]
Khu vực miền bắc chi nhánh Lạng Sơn

**Comment by thuanzero94** [comment]
Khu vực miền bắc chi nhánh vĩnh phúc - bị lỗi tương tự

**Comment by caohuongls** [comment]
@trvqhuy Chi nhánh Lạng Sơn hôm nay thấy tự lên trở lại r nhé b

**Comment by trvqhuy** [comment]
Hệ thống EVNNPC - EVN chi nhánh miền Bắc đã được bảo trì, dẫn đến việc integration không thể fetch dữ liệu vào thời điểm nói trên.

Đây không phải là bug thuộc code của Integration.
