### ISSUE TITLE
[EVNCPC & EVNSPC] Failed to connect to EVN Server.

### ISSUE THREAD

**Issue by nhotranqn** [trvqhuy/nestup_evn#12]
Lỗi Không thể kết nối đến máy chủ EVN. mặc dầu đã đúng tất cả thông tin

**Comment by trvqhuy** [comment]
@nhotraqn nhờ bạn gửi thông tin chi nhánh EVN nhé

**Comment by nhotranqn** [comment]
![IMG_20221215_122835](https://user-images.githubusercontent.com/104377944/207780027-468853c6-c9e5-4057-b9ee-fa05f4dd9ac2.jpg)
Evn Miền trung đó anh. Đăng nhập web user, pass bình thường .

**Comment by xuonghuynh** [comment]
mình cũng bị EVN Miền Nam: Failed to connect to EVN Server.

**Comment by trvqhuy** [comment]
Xin chào @nhotranqn và @xuonghuynh , lỗi trên xảy ra do phía server EVN đã và đang được bảo trì.

Vì đây không phải bug của Integration, nên các bạn hãy kiên nhẫn chờ đến khi bên server hoạt động lại bình thường nhé.
