### ISSUE TITLE
[EVNHANOI] Unavailable sensors

### ISSUE THREAD

**Issue by softhuntermike** [trvqhuy/nestup_evn#13]

**Comment by softhuntermike** [comment]
EVN Hanoi, ko fetch được thông tin tiêu thụ điện về được

**Comment by trvqhuy** [comment]
Hi @softhuntermike , cho em hỏi bác ở khu vực nào vậy ạ?

Em có test thử một mã KH ở khu vực quận Hoàng Mai thì Integration vẫn hoạt động bình thường nhé.
![Capture](https://user-images.githubusercontent.com/88963333/209454931-a71ec4fa-85b6-470c-b5cb-d8ef30272de6.PNG)
