### ISSUE TITLE
[EVN Miền Bắc] Lỗi khi đăng ký nhiều đồng hồ: (Unexpected error. Please contact github@trvqhuy)

### ISSUE THREAD

**Issue by tuansacer** [trvqhuy/nestup_evn#14]
![image](https://user-images.githubusercontent.com/37577474/212268371-a2673af2-19a8-4794-ab83-f04d914d4a5f.png)

Mình muốn add nhiều đồng hồ thì đăng ký cái thứ 2 thì bị lỗi này (Cái thứ 1 đã thành công). Vui lòng kiểm tra giúp.

**Comment by trvqhuy** [comment]
chào @tuansacer , bạn sử dụng 2 tài khoản khác nhau cho 2 mã khách hàng EVN phải không ạ?

**Comment by tuansacer** [comment]
Đúng rồi bạn, nhà mình có 4 cái đồng hồ, mỗi cái là 1 tài khoản/mã khách hàng khác nhau (PA***1, PA***2, PA***3, Pa***4)
-> Giờ mình muốn quản lý tất cả thì cách nào không bạn ?

**Comment by trvqhuy** [comment]
Thường thì sử dụng nhiều mã khách hàng tương ứng với nhiều tài khoản khác nhau đều được.

Trường hợp này mình thấy bạn là người đầu tiên gặp phải lỗi trên, bạn có thể chụp phần logs cho mình xem không?

**Comment by tuansacer** [comment]
![image](https://user-images.githubusercontent.com/37577474/212808304-1b6f445e-bd4a-4220-8382-ec070df729f2.png)
Mình vừa thử add lại thì hôm nay tự nhiên lại được bạn ạ. Hixhix
Cũng chưa hiểu lý do vì thông tin nhập thì vẫn như cũ + HA phiên bản mới nhất.

Tuy nhiên cảm ơn bạn đã hỗ trợ, mình xin đóng issue ở đây nhé !
