### ISSUE TITLE
[Đề xuất tính năng] Thêm Sensor Entity vào Energy Dashboard

### ISSUE THREAD

**Issue by tuansacer** [trvqhuy/nestup_evn#15]
Chào bạn, cho mình hỏi cấu hình chỗ "Energy > Electricity Grid" nhưng chỉ chọn được 1 Sensor là "Chỉ số tạm chốt" như hình:
![image](https://user-images.githubusercontent.com/37577474/216491080-621a6bf7-65eb-4c94-b93c-2ca962b7f761.png)

Mình có 2 câu hỏi:
**1- Mình chọn cái Sensor này nhưng thấy dữ liệu không thay đổi hàng ngày, không biết như vậy đúng hay sai ?**
![image](https://user-images.githubusercontent.com/37577474/216491404-f85a96da-910c-4afe-b1cc-db8c5594aa42.png)

**2- Mình muốn chọn một Sensor khác để có thể theo dõi về số điện/tiền điện (thay đổi hàng ngày để dễ so sánh) thì làm cách nào ?**
![image](https://user-images.githubusercontent.com/37577474/216491757-cf4036d5-abde-45b7-bd1e-773e1bd98e33.png)

Xin cảm ơn!

**Comment by trvqhuy** [comment]
Hi @tuansacer, mình đã có cố gắng thêm tính năng thêm thông tin **chỉ số tạm chốt** vào phần **Energy** của HomeAssistant, tuy nhiên mọi thứ có vẻ như không được thuận lợi cho lắm.

Mình sẽ vẫn tiếp tục tìm cách và thông báo ngay sau khi thành công điều chỉnh source code của integration.

Xin cảm ơn bạn vì những đóng góp này.

**Comment by NgTueLinh** [comment]
Với Energy, đang để  cho add Sensor Entity "Chỉ số tạm chốt" nên việc khai thác chưa đúng ý nghĩa lắm vì HA thu thập chỉ số tiêu thụ hằng ngày. 
Nếu cho phép khai thác Sensor Entity **"Sản lượng hôm qua"** thì sẽ đúng với chức năng quản lý của Energy
Trân trọng tham gia ý kiến.
