### ISSUE TITLE
Lỗi không xác định. Xin hãy report tới github@trvqhuy.[Chi nhánh EVN] Mô tả chung về lỗi

### ISSUE THREAD

**Issue by datvista** [trvqhuy/nestup_evn#18]
**Mô tả lỗi / Describe the bug**
Mô tả ngắn gọn lỗi bạn đã gặp phải trong quá trình cài đặt hoặc sử dụng.

**Logs**
Thêm phần logs báo lỗi của HA có liên quan đến Integration.

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [e.g. Linux]
 - HA platform: [e.g. Core]
 - HA Version: [e.g. 2022.7.0]

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [e.g. HACS] (cách cài đặt Integration)
 - Version: [e.g. v.2.1.0]

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by trvqhuy** [comment]
Issue này không hợp lệ do không cung cấp đủ thông tin.
