### ISSUE TITLE
EVNNPC: lỗi không xác định

### ISSUE THREAD

**Issue by quangvinh9x** [trvqhuy/nestup_evn#2]
![image](https://user-images.githubusercontent.com/71742958/190204054-40b75260-43c0-4066-a80e-80c1b41de4f6.png)

Admin xem giúp xem tài khoản này không đăng nhập được

**Comment by trvqhuy** [comment]
@quangvinh9x cho mình hỏi bạn đã từng login vào web hoặc app của EVNNPC để theo dõi sản lượng điện theo ngày chưa ạ?

**Comment by quangvinh9x** [comment]
> @quangvinh9x cho mình hỏi bạn đã từng login vào web hoặc app của EVNNPC để theo dõi sản lượng điện theo ngày chưa ạ?

Mình vẫn vào xem bình thường mà

**Comment by trvqhuy** [comment]
@quangvinh9x bạn vào app của EVN phần sản lượng theo ngày chụp cho mình xem thử nhé

**Comment by quangvinh9x** [comment]
![20220915_101954.jpg](https://user-images.githubusercontent.com/71742958/190306165-ea869950-8307-4a9b-997b-adfdc2f649f1.jpg)

**Comment by trvqhuy** [comment]
@quangvinh9x do api mình lấy từ app EVNNPC nên bạn chụp phần sản lượng ngày trong ứng dụng IOS hoặc Android giúp mình nhé

**Comment by quangvinh9x** [comment]
![Screenshot_20220915-103047_EVNNPCCSKH.jpg](https://user-images.githubusercontent.com/71742958/190307505-784be0b7-d125-4fa7-aef3-2f4dbd1bce97.jpg)

**Comment by trvqhuy** [comment]
@quangvinh9x bạn thử thiết lập lại một lần nữa và cho mình xem phần logs của HA nhé

**Comment by quangvinh9x** [comment]
![20220915_103744.jpg](https://user-images.githubusercontent.com/71742958/190308331-337bf58d-5f69-4dfe-97d4-2d31facd4a5f.jpg)

**Comment by quangvinh9x** [comment]
Mình mà lấy dc địa chỉ ip của dữ liệu npc như ở git này thì chắc đơn giản hơn nhỉ https://github.com/phanmemkhoinghiep/evnhanoi


Với nữa là đồng hồ 3 pha 2 chiều, vẫn có đo xa bạn chưa dev dc à

**Comment by trvqhuy** [comment]
- EVNNPC hiện tại không thể request trực tiếp đến địa chỉ IP cố định như vậy bạn à, thậm chí muốn request đến API trên website để lấy data cũng bất khả thi do phần bảo mật captcha login. Hiện tại API để lấy data của NPC là cũng do mình tự tìm.

- Mỗi khi muốn ra mắt thêm một tính năng gì đó thì mình phải cân nhắc tính khả thi cho cả 5 tổng công ty EVN, do Integration này mình tạo ra với mục tiêu khả dụng cho cả cộng đồng HA toàn quốc, thêm nữa do mình không có partner nên việc release ra tính năng mới sẽ tốn khá nhiều thời gian.

- Hiện tại mục tiêu của mình vẫn là hoàn thiện phần điện sinh hoạt thông thường trước, rồi sau đó sẽ cân nhắc là có tiếp tục với điện 3 pha, điện mặt trời hay không.

**Comment by trvqhuy** [comment]
- Về lỗi của bạn, theo mình **đoán** là do khu vực/hộ của bạn sử dụng một loại công tơ khác với loại công tơ mình hỗ trợ cho các bạn thuộc EVNNPC, nên dữ liệu trả về nó cũng không giống với code của mình.
- Mình sẽ **close issue** này tại đây, bạn cứ inbox trực tiếp Facebook mình, gửi cho mình tài khoản EVN để mình hỗ trợ riêng cho trường hợp của bạn nhé.
