### ISSUE TITLE
[EVN Thuận An] Ngày đầu kì là 24 dùm e đã chỉnh ngày khác lúc Setup

### ISSUE THREAD

**Issue by iwbrhwfy-source** [trvqhuy/nestup_evn#21]
**Mô tả lỗi / Describe the bug**
Lúc Setup dùm e chọn ngày đầu kì là bao nhiêu thì khi setup xong nó vẫn hiện là 24

**Logs**

**Ảnh chụp / Screenshots**
![image](https://user-images.githubusercontent.com/59449747/227857717-4b49ed44-ebf3-4723-902a-30e93ec42d9d.png)

**Server (thông tin máy chủ đang chạy HA):**
 - OS: x86
 - HA platform: Supervisor 
 - HA Version: 2023.03.2

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: v.2.1.0

**Thông tin thêm**

**Comment by iwbrhwfy-source** [comment]
https://user-images.githubusercontent.com/59449747/228412160-0af26b1d-90a8-4361-948a-66132d36a0f5.MOV

**Comment by trvqhuy** [comment]
Chào @iwbrhwfy-source , lỗi này có thể do dữ liệu từ EVN với mã khách hàng của bạn không tồn tại trong khoảng ngày 8-24 của tháng 2.

Nhờ bạn kiểm tra lại nhé.

**Comment by iwbrhwfy-source** [comment]
> Chào @iwbrhwfy-source , lỗi này có thể do dữ liệu từ EVN với mã khách hàng của bạn không tồn tại trong khoảng ngày 8-24 của tháng 2.
> 
> Nhờ bạn kiểm tra lại nhé.

Dạ chuẩn r ạ nay e add lại thử ngày 1 thì được r. Cảm ơn b nhiều
