### ISSUE TITLE
[homeassistant.config_entries] Error setting up entry PD05000040043 for nestup_evn

### ISSUE THREAD

**Issue by khaisilk1910** [trvqhuy/nestup_evn#22]
Hiện tại bản mới **Home Assistant 2023.5.0** bị lỗi lấy dữ liệu từ điện lực.
Lỗi như bên dưới.
Nhờ bạn sớm khắc phục lỗi.
Cảm ơn!
[home-assistant_2023-05-04T03-51-27.623Z.log](https://github.com/trvqhuy/nestup_evn/files/11392784/home-assistant_2023-05-04T03-51-27.623Z.log)

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/nestup_evn/__init__.py:12
Integration: EVN Data Fetcher (documentation, issues)
First occurred: 6:26:56 AM (5 occurrences)
Last logged: 6:26:56 AM

Error setting up entry PD05000040043 for nestup_evn
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nestup_evn/__init__.py", line 12, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, ["sensor"])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by Builder-DE-TH** [comment]
I have the same error

**Comment by vboyhn** [comment]
i have same with new HA: 2023.5.0

**Comment by trvqhuy** [comment]
Sorry guys, the new version of HA has changed some internal APIs, and has not been supported by the integration yet.

Please stay still, and wait for new updates from the author, or (hopefully) other participants.

**Comment by hieulq** [comment]
@trvqhuy please review PR #23 to fix this issue

**Comment by vboyhn** [comment]
> @trvqhuy please review PR #23 to fix this issue
thanks.
