### ISSUE TITLE
[EVN Bắc từ liêm HN] Không load được device

### ISSUE THREAD

**Issue by hongthang1110** [trvqhuy/nestup_evn#24]
**Mô tả lỗi / Describe the bug**
Sau khi nâng cấp Hass lên bản mới Home Assistant 2023.5.2 thì bị lỗi không load được device EVN

**Logs**
Logger: homeassistant.config_entries
Source: custom_components/nestup_evn/__init__.py:12
Integration: EVN Data Fetcher ([documentation](https://github.com/trvqhuy/nestup_evn/), [issues](https://github.com/trvqhuy/nestup_evn/issues))
First occurred: 09:31:00 (1 occurrences)
Last logged: 09:31:00

Error setting up entry PD30000211273 for nestup_evn
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nestup_evn/__init__.py", line 12, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, ["sensor"])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Ảnh chụp / Screenshots**
![image](https://user-images.githubusercontent.com/5145311/236655027-eecbde5d-6e01-4c4c-b097-755b7776e7ca.png)
![image](https://user-images.githubusercontent.com/5145311/236655058-c11af677-d90e-4172-9f82-aa644ca4c7c1.png)

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [Linux]
 Home Assistant 2023.5.2
Supervisor 2023.04.1
Phiên bản Frontend: 20230503.3 - latest

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [HACS]
Thông tin thiết bị
Vietnam EVN Monitor
bởi Nestup Co.
Firmware: 2.1.0
Hardware: by Điện Lực Bắc Từ Liêm

**Thông tin thêm**
Sau khi nâng cấp Hass lên bản mới Home Assistant 2023.5.2 thì bị lỗi không load được device EVN

**Comment by datdp** [comment]
![image](https://user-images.githubusercontent.com/3733699/236690457-3299b29e-1672-41e5-ba2d-7e2439277572.png)
Cũng lỗi như bác ở trên. Điện lực Nam Từ Liêm - Hà Nội

**Comment by justintrann** [comment]
The same to you at EVN Ho Chi Minh City
