### ISSUE TITLE
EVN Hà Nội - Lỗi Setup

### ISSUE THREAD

**Issue by mcnguyen33r** [trvqhuy/nestup_evn#25]
**Mô tả lỗi / Describe the bug**
Không setup được (Failed to set up) mặc dù thông tin điền vào chính xác

**Logs**
2023-05-08 14:28:28.918 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nestup_evn which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-08 14:29:01.467 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PD11000027XXX for nestup_evn
File "/config/custom_components/nestup_evn/__init__.py", line 12, in async_setup_entry

Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/nestup_evn/__init__.py:12
Integration: EVN Data Fetcher ([documentation](https://github.com/trvqhuy/nestup_evn/), [issues](https://github.com/trvqhuy/nestup_evn/issues))
First occurred: 2:29:01 PM (1 occurrences)
Last logged: 2:29:01 PM

Error setting up entry PD11000027XXX for nestup_evn
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nestup_evn/__init__.py", line 12, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, ["sensor"])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Ảnh chụp / Screenshots**
![image](https://user-images.githubusercontent.com/71171878/236775444-5ba38c60-2369-4609-919f-a7ccff839f18.png)
**Server (thông tin máy chủ đang chạy HA):**
Home Assistant 2023.5.2
Supervisor 2023.04.1
Frontend 20230503.3 - latest

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: v2.1.0

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by christianonpele** [comment]
same with EVN Saigon. 

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nestup_evn/__init__.py", line 12, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, ["sensor"])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'`

**Comment by haind13** [comment]
cacs b

> **Mô tả lỗi / Describe the bug** Không setup được (Failed to set up) mặc dù thông tin điền vào chính xác
> 
> **Logs** 2023-05-08 14:28:28.918 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nestup_evn which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant 2023-05-08 14:29:01.467 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PD11000027XXX for nestup_evn File "/config/custom_components/nestup_evn/**init**.py", line 12, in async_setup_entry
> 
> Log Details (ERROR) This error originated from a custom integration. Logger: homeassistant.config_entries Source: custom_components/nestup_evn/**init**.py:12 Integration: EVN Data Fetcher ([documentation](https://github.com/trvqhuy/nestup_evn/), [issues](https://github.com/trvqhuy/nestup_evn/issues)) First occurred: 2:29:01 PM (1 occurrences) Last logged: 2:29:01 PM
> 
> Error setting up entry PD11000027XXX for nestup_evn Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/nestup_evn/**init**.py", line 12, in async_setup_entry hass.config_entries.async_setup_platforms(entry, ["sensor"]) AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
> 
> **Ảnh chụp / Screenshots** ![image](https://user-images.githubusercontent.com/71171878/236775444-5ba38c60-2369-4609-919f-a7ccff839f18.png) **Server (thông tin máy chủ đang chạy HA):** Home Assistant 2023.5.2 Supervisor 2023.04.1 Frontend 20230503.3 - latest
> 
> **Integration (thông tin phiên bản Integration đã cài đặt):**
> 
> * Installation method: HACS
> * Version: v2.1.0
> 
> **Thông tin thêm** Thêm những thông tin khác ngoài các thông tin kể trên.

Các bạn download lại bản mới fix 2 ngày trước, rồi add devices lại là đc nhé! mình đã cài thành công

**Comment by mcnguyen33r** [comment]
Thử lại không được bạn ạ. 
1. Xóa hết thư mục nestup_evn
2. Khởi động lại HA
3. Vào HACS tải lại EVN Fetcher
4. Khởi động lại HA
5. Setup lại EVN
6. Vẫn lỗi như vậy
![image](https://user-images.githubusercontent.com/71171878/236968236-a6297f7e-2cd1-4924-8028-d0e2647e6f05.png)
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/nestup_evn/__init__.py:12
Integration: EVN Data Fetcher ([documentation](https://github.com/trvqhuy/nestup_evn/), [issues](https://github.com/trvqhuy/nestup_evn/issues))
First occurred: 7:59:38 AM (1 occurrences)
Last logged: 7:59:38 AM

Error setting up entry PD1100002XXX for nestup_evn
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nestup_evn/__init__.py", line 12, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, ["sensor"])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by haind13** [comment]
> Thử lại không được bạn ạ.
> 
> 1. Xóa hết thư mục nestup_evn
> 2. Khởi động lại HA
> 3. Vào HACS tải lại EVN Fetcher
> 4. Khởi động lại HA
> 5. Setup lại EVN
> 6. Vẫn lỗi như vậy
>    ![image](https://user-images.githubusercontent.com/71171878/236968236-a6297f7e-2cd1-4924-8028-d0e2647e6f05.png)
>    Log Details (ERROR)
>    This error originated from a custom integration.
>    Logger: homeassistant.config_entries
>    Source: custom_components/nestup_evn/**init**.py:12
>    Integration: EVN Data Fetcher ([documentation](https://github.com/trvqhuy/nestup_evn/), [issues](https://github.com/trvqhuy/nestup_evn/issues))
>    First occurred: 7:59:38 AM (1 occurrences)
>    Last logged: 7:59:38 AM
> 
> Error setting up entry PD1100002XXX for nestup_evn Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/nestup_evn/**init**.py", line 12, in async_setup_entry hass.config_entries.async_setup_platforms(entry, ["sensor"]) AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

bạn thử cách cài ko qua HACS đi :D

**Comment by trvqhuy** [comment]
Chào các bạn,

Các lỗi liên quan đến 'async_setup_platforms'  đã được fix ở version mới nhất v2.2.0.

Hãy cập nhật phiên bản mới nhất để tiếp tục sử dụng Integration.
