### ISSUE TITLE
[Đề xuất tính năng mới] Lịch cắt điện

### ISSUE THREAD

**Issue by haigaru** [trvqhuy/nestup_evn#30]
Bổ sung thêm lịch cắt điện được không bác Huy ơi

**Comment by trvqhuy** [comment]
Hiện tại hệ thống thông báo lịch cắt điện chưa được đồng bộ giữa các chi nhánh EVN toàn quốc, dẫn đến việc rất khó để tích hợp lịch cắt điện vào Integration. Tuy nhiên, trong tương lai có thể sẽ có tính năng này.
