### ISSUE TITLE
EVNSPC - Lỗi kết nối

### ISSUE THREAD

**Issue by thangnd85** [trvqhuy/nestup_evn#31]
**Mô tả lỗi / Describe the bug**
Lỗi không kết nối được server

**Logs**
Thêm phần logs báo lỗi của HA có liên quan đến Integration.
Logger: custom_components.nestup_evn.nestup_evn
Source: custom_components/nestup_evn/nestup_evn.py:83
Integration: EVN Data Fetcher ([documentation](https://github.com/trvqhuy/nestup_evn/), [issues](https://github.com/trvqhuy/nestup_evn/issues))
First occurred: 20:03:56 (3 occurrences)
Last logged: 20:05:50

Cannot connect to EVN Server while requesting new data: status code 500

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.
<img width="400" alt="image" src="https://github.com/trvqhuy/nestup_evn/assets/22338081/621d73c5-2fc6-4001-8b85-0dbdbf31c4cc">

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [e.g. Linux]
 - HA platform: [e.g. Core]
 - HA Version: [e.g. 2022.7.0]

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [e.g. HACS] (cách cài đặt Integration)
 - Version: [e.g. v.2.1.0]

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by trvqhuy** [comment]
Đây không phải lỗi từ integration, các mã khách hàng từ EVNSPC vẫn hoạt động ổn định.
