### ISSUE TITLE
[Chi nhánh EVN] Lỗi không lấy được dữ liệu EVN Hà Nội

### ISSUE THREAD

**Issue by datdp** [trvqhuy/nestup_evn#33]
**Mô tả lỗi / Describe the bug**
Lỗi không lấy được dữ liệu EVN Hà Nội

**Logs**
This error originated from a custom integration.

Logger: custom_components.nestup_evn.sensor
Source: custom_components/nestup_evn/sensor.py:113
Integration: EVN Data Fetcher (documentation, issues)
First occurred: October 17, 2023 at 09:14:31 (5 occurrences)
Last logged: 09:14:35

[EVN ID PD05000168857] Could not fetch new data - 401
![image](https://github.com/trvqhuy/nestup_evn/assets/3733699/f126e524-0bd1-46cc-9959-bfc15add4106)

![image](https://github.com/trvqhuy/nestup_evn/assets/3733699/7125c6b1-02fb-42d1-8b8f-cee3e4db9be7)

**Server (thông tin máy chủ đang chạy HA):**
![image](https://github.com/trvqhuy/nestup_evn/assets/3733699/627a3ba7-377b-4c11-9cca-38e1a0ff2476)

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version:  v.2.1.0

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by cuongtst** [comment]
bỏ thôi ! bên điện lực thêm xác thực captcha đăng nhập !

**Comment by trvqhuy** [comment]
Đây không phải lỗi từ integration, các mã khách hàng từ EVNHANOI vẫn hoạt động ổn định.
