### ISSUE TITLE
[Chi nhánh EVN] HCM không set được ngày đầu kỳ (ngày cuối cùng của tháng) không cho set ngày 1 (-1)

### ISSUE THREAD

**Issue by huydats** [trvqhuy/nestup_evn#35]
**Mô tả lỗi / Describe the bug**
Mô tả ngắn gọn lỗi bạn đã gặp phải trong quá trình cài đặt hoặc sử dụng.

**Logs**
Thêm phần logs báo lỗi của HA có liên quan đến Integration.

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [e.g. Linux]
 - HA platform: [e.g. Core]
 - HA Version: [e.g. 2022.7.0]

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [e.g. HACS] (cách cài đặt Integration)
 - Version: [e.g. v.2.1.0]

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by trvqhuy** [comment]
Hiện tại cơ sở dữ liệu từ EVNHCMC đang gặp vấn đề, đây là lỗi từ EVN endpoint, không phải do integration.
