### ISSUE TITLE
[Chi nhánh EVN] CPC Miền Trung lỗi đăng nhập

### ISSUE THREAD

**Issue by Cuongict47** [trvqhuy/nestup_evn#37]
**Mô tả lỗi / Describe the bug**
Lỗi đăng nhập báo sai userr/password mặc dù đã đúng
![image](https://github.com/trvqhuy/nestup_evn/assets/86100352/dcc35ba9-073a-46e5-86c3-529ea7a34c3f)

**Logs**
Thêm phần logs báo lỗi của HA có liên quan đến Integration.

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.
![image](https://github.com/trvqhuy/nestup_evn/assets/86100352/ab13079d-bbb1-4178-814c-92689c6af1ff)

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [e.g. Linux]
 - HA platform: Supervisor
 - HA Version: 2023.11.3

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: [v.2.2.0

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by trvqhuy** [comment]
Đây không phải lỗi từ integration, các mã khách hàng từ EVNCPC vẫn hoạt động ổn định.
