### ISSUE TITLE
[Chi nhánh EVN] Mô tả chung về lỗi

### ISSUE THREAD

**Issue by trung729** [trvqhuy/nestup_evn#39]
**Mô tả lỗi / Describe the bug**
Sau khi nâng cấp lên Home Assistant lên bản mới, netsup-Evn không đọc được dữ liệu từ EVN nữa

**Logs**
Thêm phần logs báo lỗi của HA có liên quan đến Integration.

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [e.g. Linux]
 - HA platform: [e.g. Core]
 - HA Version: [e.g. 2022.7.0]

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [e.g. HACS] (cách cài đặt Integration)
 - Version: [e.g. v.2.1.0]

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by trvqhuy** [comment]
Xin hãy cung cấp thêm các thông tin chi tiết khác.
