### ISSUE TITLE
Thay đổi ngày bắt đầu hóa đơn về đầu tháng

### ISSUE THREAD

**Issue by phankhanhpvk** [trvqhuy/nestup_evn#41]
Hà Nội đã chuyển ngày bắt đầu hóa đơn về đầu tháng, nhờ ad update ạ

**Comment by trvqhuy** [comment]
Hi @phankhanhpvk, vì đây là 1 integration dành cho tất cả chi nhánh EVN trên toàn quốc, nên Integration phải có phần khai báo ngày bắt đầu hóa đơn và phải được tùy chỉnh dựa trên mã KH của từng user.

Nếu muốn chỉnh sửa ngày bắt đầu hóa đơn, bạn thông cảm khởi tạo lại bước Integration Setup nhé.
