### ISSUE TITLE
[EVNNPC] không kết nối được máy chủ/Lỗi đăng nhập

### ISSUE THREAD

**Issue by HanAnh97** [trvqhuy/nestup_evn#42]
**Mô tả lỗi / Describe the bug**
App EVNNPC cập nhật mới có thêm captcha bước đăng nhập, trên hass đăng nhập báo lỗi kết nối máy chủ EVN
.

**Ảnh chụp / Screenshots**
![CD0684A3-F491-4217-A723-6E418AFE790F](https://github.com/trvqhuy/nestup_evn/assets/25389981/2e8f850e-63f1-4f3e-92a8-7af7a3ad86fc)

![BF081ADB-1FF7-4C6E-9314-5968BCFC90D1](https://github.com/trvqhuy/nestup_evn/assets/25389981/633b688c-9f33-4cc1-b33f-511324d25471)
hơn.

![551A1E9B-9FB7-4DC1-9A50-DBAB4E1310A6](https://github.com/trvqhuy/nestup_evn/assets/25389981/197b6f97-fbef-4e18-8499-5d410ba37127)

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [Linux]
 - HA platform: [Core]
 - HA Version: [2024.2.2]

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [HACS]
 - Version: [v.2.1.0]

**Thông tin thêm**
Đăng nhập thông tin trên app EVNNPC vẫn hiện đầy đủ

**Comment by phanquynhatminh** [comment]
Mình đã tìm ra nguyên nhân gây lỗi. 
Sử dụng web trên máy tính để vô homeassistant để nhập thì ok.. nhưng nhập trên app homeassistant trên điện thoại thì không được.

**Comment by trvqhuy** [comment]
Hiện tại Integration đã ngừng hỗ trợ cho EVNNPC chi nhánh miền Bắc, do EVN khu vực này đã thêm CAPTCHA vào bước đăng nhập.

**Comment by chautruongthinh** [comment]
> Hiện tại Integration đã ngừng hỗ trợ cho EVNNPC chi nhánh miền Bắc, do EVN khu vực này đã thêm CAPTCHA vào bước đăng nhập.

Hiện tại EVNNPC đã không còn CAPTCHA, nên mở lại bug này đi bác @trvqhuy
