### ISSUE TITLE
[EVN miền nam] sản lượng ngày hôm nay báo hôm qua, hôm qua báo hôm kia, tổng sản lượng sai. 

### ISSUE THREAD

**Issue by ttt19922010** [trvqhuy/nestup_evn#45]
**Mô tả lỗi / Describe the bug**
Mô tả ngắn gọn lỗi bạn đã gặp phải trong quá trình cài đặt hoặc sử dụng.

**Logs**
Thêm phần logs báo lỗi của HA có liên quan đến Integration.

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [e.g. Linux]
 - HA platform: [e.g. Core]
 - HA Version: [e.g. 2022.7.0]

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [e.g. HACS] (cách cài đặt Integration)
 - Version: [e.g. v.2.1.0]

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by trvqhuy** [comment]
Bạn update và sử dụng phiên bản v2.4.2 nhé.
