### ISSUE TITLE
[EVNHCMC] Nhập đúng thông tin login nhưng báo lỗi Unexpected error. Please contact github@trvqhuy.

### ISSUE THREAD

**Issue by tphucibc** [trvqhuy/nestup_evn#46]
**Mô tả lỗi / Describe the bug**
Làm theo hướng dẫn, đến bước nhập username và password thì báo lỗi Unexpected error. Please contact github@trvqhuy. nếu cấu hình Billing Start Date là ngày 1, các ngày còn lại thì ok

**Ảnh chụp / Screenshots**
![image](https://github.com/trvqhuy/nestup_evn/assets/708808/51700d37-6966-4b91-97b4-a296173e1d4c)

**Server (thông tin máy chủ đang chạy HA):**
- Core 2024.5.1
- Supervisor 2024.04.4
- Operating System 12.2
- Frontend 20240501.0

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: v.2.2.0

**Thông tin thêm**
Mình có thử trường hợp nhập sai pass thì có báo lỗi là "Invalid EVN authentication. Please recheck your Username and Password." cho nên lỗi trên là nhập đúng thông tin login nhưng vẫn lỗi

**Comment by tungthanh500** [comment]
Bug là do chọn start date là 1. Thực tế tất cả EVN đều chuyển start date về 1 hết rồi bác dev ơi
