### ISSUE TITLE
[EVNHCMC] bị lỗi khi chọn giá trị 1 cho ngày đầu kỳ

### ISSUE THREAD

**Issue by vdt2210** [trvqhuy/nestup_evn#47]
lúc chọn ngày đầu kỳ hình như bị truyền sai giá trị. phải nhích lên ngày 2 mới ko bị lỗi với ra ngày đầu kỳ là ngày 1

![image](https://github.com/trvqhuy/nestup_evn/assets/87288753/8b3c1f16-9d33-4b2a-a9e7-d1e455979948)

 - OS: Linux (máy ảo)
![image](https://github.com/trvqhuy/nestup_evn/assets/87288753/01c63342-ad72-4ad1-9e59-034c4330688d)

 - Installation method: HACS
 - Version: v.2.1.0

**Comment by alohaquando** [comment]
Mình cũng bị lỗi này. Ngày đầu kì của mình cũng là ngày 1

**Comment by trvqhuy** [comment]
Đã fix lỗi đầu kì cho EVNHCMC, mời các bạn update phiên bản mới nhất v2.4.2 và sử dụng nhé
