### ISSUE TITLE
[EVN HCM] unavailable + số thống kê ko đúng

### ISSUE THREAD

**Issue by vdt2210** [trvqhuy/nestup_evn#51]
Đôi khi trả về unavaible hoặc trả về giá trị 0 trước khi có thông số mới

![image](https://github.com/trvqhuy/nestup_evn/assets/87288753/e0452683-8d6c-4fef-92fa-53885754e3c1)
![image](https://github.com/trvqhuy/nestup_evn/assets/87288753/3991b5e9-bea4-41f2-80f9-90ca3deb764b)

 - OS: Debian 12
 - HA platform: core
 - HA Version: 2024.6.4

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: v.2.4.1

 Bên tab energy lấy thông số tổng thay vì số đã thay đổi. ver cũ lấy thông số thay đổi

**Comment by trvqhuy** [comment]
Mình đã fix lỗi này ở phiên bản mới nhất nhé bạn.
