### ISSUE TITLE
[EVN HCM] Thông số hằng ngày bị lệch

### ISSUE THREAD

**Issue by vdt2210** [trvqhuy/nestup_evn#52]
Thông số hằng ngày bị lệch so với app

![image](https://github.com/trvqhuy/nestup_evn/assets/87288753/a7c70c74-fe90-4d21-ac2f-c79c504349d6)
![image](https://github.com/trvqhuy/nestup_evn/assets/87288753/bf7bbaa1-7cc0-441d-8baa-1e7b8c813fe9)

- OS: Debian 12
- HA platform: core
- HA Version: 2024.6.4

- Installation method: HACS
- Version: v.2.4.1

**Comment by anhnvme** [comment]
@vdt2210 bạn cho mình xin cách tạo chart như hình trên đầu của bạn với

**Comment by vdt2210** [comment]
> @vdt2210 bạn cho mình xin cách tạo chart như hình trên đầu của bạn với

này trong mục năng lượng nha bạn. add chỉ số tạm chốt vô là nó tự có nha
![image](https://github.com/user-attachments/assets/e5e706b0-1e01-42b1-9b4c-7378519fd937)

**Comment by anhnvme** [comment]
> > @vdt2210 bạn cho mình xin cách tạo chart như hình trên đầu của bạn với
> 
> này trong mục năng lượng nha bạn. add chỉ số tạm chốt vô là nó tự có nha ![image](https://private-user-images.githubusercontent.com/87288753/357273987-e5e706b0-1e01-42b1-9b4c-7378519fd937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjMxNTcsIm5iZiI6MTcyMzUyMjg1NywicGF0aCI6Ii84NzI4ODc1My8zNTcyNzM5ODctZTVlNzA2YjAtMWUwMS00MmIxLTliNGMtNzM3ODUxOWZkOTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA0MjA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYmE1MTAzYTdmYzk4ZTNmNjcwY2Y5ZGFkYzg0MTg4Njc0MmI4MmRjMWJkYmRkMzI3MjNmMjM4MjJhZmMwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OIIi05sGpuOCi7X2iLxuyzqlWb5NshbDfEkfRLXHOIk)

cám ơn bạn nhé
