### ISSUE TITLE
Mô tả lỗi

### ISSUE THREAD

**Issue by kylephp** [trvqhuy/nestup_evn#54]
**Mô tả lỗi / Describe the bug**
![image](https://github.com/user-attachments/assets/c1ed3195-0834-4101-9414-d28f082fa138)

**Logs**
`Logger: homeassistant.setup
Source: setup.py:269
First occurred: 3:00:48 PM (1 occurrences)
Last logged: 3:00:48 PM

Setup failed for custom integration 'nestup_evn': Requirements for nestup_evn not found: ['voluptuous==0.13.1'].`
**Ảnh chụp / Screenshots**
![image](https://github.com/user-attachments/assets/9950d495-8125-480d-9fc8-89363b63954b)

**Server (thông tin máy chủ đang chạy HA):**
![image](https://github.com/user-attachments/assets/c6ec1307-39f1-439f-ac4a-53993d2569e3)

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: 
![image](https://github.com/user-attachments/assets/815e31fd-4c10-4f20-bc66-7406b04159a1)

**Comment by duytung1009** [comment]
Mình vừa gặp lỗi này sau khi update lên Home Assistant Core 2024.8. Mình có tạo một PR fix issue này ở đây: https://github.com/trvqhuy/nestup_evn/pull/55

Ai đang bị lỗi thì có thể dùng File editor mở file `/homeassistant/custom_components/nestup_evn/manifest.json` rồi sửa phần `"voluptuous==0.13.1"` thành `"voluptuous"`, restart lại là sẽ hết lỗi.

**Comment by trvqhuy** [comment]
Cảm ơn bạn @duytung1009
