### ISSUE TITLE
[EVN Hà Nội] Sau khi update HASS 2024.8.0 không hoạt động

### ISSUE THREAD

**Issue by khaisilk1910** [trvqhuy/nestup_evn#56]
**Mô tả lỗi / Describe the bug**
Sau khi update HASS 2024.8.0 không hoạt động.

**Logs**
Thêm phần logs báo lỗi của HA có liên quan đến Integration.

**Ảnh chụp / Screenshots**
![image](https://github.com/user-attachments/assets/627a4383-7af9-4822-8626-001e318e30b9)

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [e.g. Linux]
 - HA platform: HASSOS
 - HA Version: 2024.8.0

**Comment by vuasia** [comment]
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 11:10:14 (1 occurrences)
Last logged: 11:10:14

Setup failed for custom integration 'nestup_evn': Requirements for nestup_evn not found: ['voluptuous==0.13.1'].
