### ISSUE TITLE
[Chi nhánh EVN] Mô tả chung về lỗi

### ISSUE THREAD

**Issue by vboyhn** [trvqhuy/nestup_evn#57]
**Mô tả lỗi / Describe the bug**
Không load được sau khi update Core lên 2024.8.0

**Logs**
Bộ ghi nhật trình: homeassistant.setup
Nguồn: setup.py:269
Lần đầu tiên xảy ra: 9:03:37 SA (1 lần xuất hiện)
Ghi nhật ký lần cuối: 9:03:37 SA

Setup failed for custom integration 'nestup_evn': Requirements for nestup_evn not found: ['voluptuous==0.13.1'].

**Ảnh chụp / Screenshots**
![image](https://github.com/user-attachments/assets/27aa4368-053d-4a62-9b5a-0cb4b398864c)

**Server (thông tin máy chủ đang chạy HA):**
Core
2024.8.0
Supervisor
2024.08.0
Operating System
12.4
Giao diện người dùng
20240806.1

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Version: 2.4.1

**Comment by quangphuc91** [comment]
mình đã tìm ra cách fix bằng cách sửa file custom_components/nestup_evn/manifest.json , đổi    

 "requirements": [
        "voluptuous==0.13.1"
   ], 

thành

 "requirements": [
        "voluptuous"
   ], 

 restart lại hass
