### ISSUE TITLE
Ngày đầu kì

### ISSUE THREAD

**Issue by hieudn3012** [trvqhuy/nestup_evn#60]
Hi bạn. Cảm ơn bạn nhiều vì tạo ra addon này. Mình có chút vấn đề muốn hỏi. Chỉ số ngày đầu kì của EVN cho số điện nhà mình đã chuyển từ ngày 11 về ngày đầu tháng, vậy có cách nào sửa ko nhỉ?

**Comment by vboyhn** [comment]
xoá addon rồi thêm lại là được nhé bạn
