### ISSUE TITLE
Cảnh báo trên hass 10.2024

### ISSUE THREAD

**Issue by fancy90** [trvqhuy/nestup_evn#63]
Bộ ghi nhật trình: homeassistant.const
Nguồn: helpers/deprecation.py:197
Lần đầu tiên xảy ra: 16:28:14 (1 lần xuất hiện)
Ghi nhật ký lần cuối: 16:28:14

ENERGY_KILO_WATT_HOUR was used from nestup_evn, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'nestup_evn' custom integration

**Comment by trvqhuy** [comment]
Đã fix ở phiên bản mới nhất nhé bạn.
