### ISSUE TITLE
[Chi nhánh EVN] Cảnh báo lỗi SSL

### ISSUE THREAD

**Issue by fancy90** [trvqhuy/nestup_evn#64]
**Logs**
Bộ ghi nhật trình: homeassistant.util.loop
Nguồn: util/loop.py:136
Lần đầu tiên xảy ra: 16:28:27 (2 lần xuất hiện)
Ghi nhật ký lần cuối: 16:28:31

Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f1a552127d0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'nestup_evn' at custom_components/nestup_evn/nestup_evn.py, line 339: ssl_context = ssl.create_default_context() (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please create a bug report at https://github.com/trvqhuy/nestup_evn/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2253, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry return await hass.data[DATA_COMPONENT].async_setup_entry(entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 328, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/nestup_evn/sensor.py", line 51, in async_setup_entry await evn_device.async_create_coordinator(hass) File "/config/custom_components/nestup_evn/sensor.py", line 137, in async_create_coordinator await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data return await self.update_method() File "/config/custom_components/nestup_evn/sensor.py", line 123, in _async_update await self.update() File "/config/custom_components/nestup_evn/sensor.py", line 82, in update self._data = await self._api.request_update( File "/config/custom_components/nestup_evn/nestup_evn.py", line 104, in request_update fetch_data = await self.request_update_evnhanoi( File "/config/custom_components/nestup_evn/nestup_evn.py", line 339, in request_update_evnhanoi ssl_context = ssl.create_default_context()

**Server (thông tin máy chủ đang chạy HA):**
 - OS: HAOS
 - HA Version: 2024.10.2]

Cài bản Phiên bản [nestup_evn](https://github.com/trvqhuy/nestup_evn) mới nhất

**Comment by trvqhuy** [comment]
Lỗi SSL đã được fix ở phiên bản mới nhất nhé bạn.
