### ISSUE TITLE
Lỗi không làm mới được dữ liệu 2 ngày nay. Home Assistant core ver 2024.10.4

### ISSUE THREAD

**Issue by leolionart** [trvqhuy/nestup_evn#68]
This error originated from a custom integration.

Logger: custom_components.nestup_evn.sensor
Source: custom_components/nestup_evn/sensor.py:113
integration: EVN Data Fetcher (documentation, issues)
First occurred: November 9, 2024 at 10:41:29 AM (31 occurrences)
Last logged: 7:58:01 AM

[EVN ID PB04020123813] Could not fetch new data - []
[EVN ID PB04020103389] Could not fetch new data - []

**Comment by duongcuong8896** [comment]
Đổi IP khác rồi reload lại Integration xem thế nào bạn

**Comment by leolionart** [comment]
Mình đăng nhập lên trang điện lực vẫn được nhưng ở đây báo fail, không biết mọi người có đang xem dữ liệu bình thường không ạ. Đổi IP public hay sao ạ? Restart modem?

**Comment by duongcuong8896** [comment]
Vâng IP public ạ hoặc nếu không dc bạn thử đặt lại mật khẩu xem, mình EVN HÀ NỘI vẫn bình thường

**Comment by trvqhuy** [comment]
Đây là lỗi xuất phát từ update gần đây của riêng khu vực EVNSPC, mời bạn xem #69 nhé

**Comment by chautruongthinh** [comment]
Nếu chúng ta đổi qua Login bằng số điện thoại và OTP thì sẽ ko có CAPTCHA
