### ISSUE TITLE
[EVNSPC] Lỗi không fetch data mới/Empty data

### ISSUE THREAD

**Issue by anhtheGM** [trvqhuy/nestup_evn#69]
không vào được bro
![2024-11-12_094409](https://github.com/user-attachments/assets/b8e6f122-56bc-4b10-9169-d4879dd32e26)

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.

**Server (thông tin máy chủ đang chạy HA):**
  - HA Version:Home Assistant

Core
2024.11.1

**Comment by chautruongthinh** [comment]
Đã không lấy được thông tin mấy ngày nay rùi

**Comment by trvqhuy** [comment]
Hiện tại EVNSPC đã update CAPTCHA để bảo mật Login Endpoint, việc này khiến cho Integration không thể request data mới được nữa (tương tự như EVNNPC), có nghĩa là tạm thời **EVNSPC sẽ không còn được hỗ trợ**.

Bài toán Bypass CAPTCHA là không dễ, nhưng mình sẽ cố gắng tìm 1 phương án khả thi để quay lại hỗ trợ cho cả 2 chi nhánh EVNSPC và EVNNPC trong tương lai. Đồng thời, mình vẫn luôn mong chờ sự giúp đỡ từ các ae Dev Việt Nam, nên nếu các bạn có những ý tưởng, hay phương án giải quyết được thì đừng ngại request mình nhé.

![image](https://github.com/user-attachments/assets/cf495922-0893-4642-a621-eb973be67b73)
![image](https://github.com/user-attachments/assets/096456b1-fc0d-4cf2-9962-cd521d1e3117)

**Comment by chautruongthinh** [comment]
https://api.cskh.evnspc.vn/api/NghiepVu/LayThongTinSanLuongTheoNgay_v1?strMaDiemDo=PB09050077784001&strFromDate=20241122&strToDate=20241123

Cách lấy dữ liệu không cần đăng nhập mình mới tìm được. @trvqhuy bác xem thử đi

**Comment by chautruongthinh** [comment]
Vừa mới tạo xong theo cách riêng của mình

![image](https://github.com/user-attachments/assets/d7292042-3024-4cb2-b90e-3bedccce205b)

**Comment by trvqhuy** [comment]
Hi @chautruongthinh , không biết bạn có thể tạo 1 push request cho mọi người cùng sử dụng được không?

**Comment by chautruongthinh** [comment]
> Hi @chautruongthinh , không biết bạn có thể tạo 1 push request cho mọi người cùng sử dụng được không?

Mình tạo ra 1 cái custom_components mới rùi. Do mình chỉ dùng evnspc. Để mình test xong sẽ public cho mọi người

**Comment by chautruongthinh** [comment]
@trvqhuy bác check gmail giúp mình cái!!

**Comment by chautruongthinh** [comment]
Cập nhật 15:30 26/11/2024 :
https://api.cskh.evnspc.vn/api/NghiepVu/LayThongTinSanLuongTheoNgay_v1?strMaDiemDo=PB09050077784001&strFromDate=20241122&strToDate=20241123
Đã không thể truy cập mà không đăng nhập

**Comment by chautruongthinh** [comment]
![image](https://github.com/user-attachments/assets/4fdc5942-b261-4b65-ba5c-a56cefe86531)

Đã hoàn thành rùi @trvqhuy

**Comment by chautruongthinh** [comment]
![image](https://github.com/user-attachments/assets/33a50173-b59c-431b-81e9-73cf91e8a43f)

Đã có thêm tính năng lịch cắt điện!!

**Comment by chautruongthinh** [comment]
> Hi @chautruongthinh, hiện tại mình không có access đến tài khoản chi nhánh EVNSPC nên không thể test được endpoints, bạn có thể confirm giúp mình là chức năng đăng nhập cũng như fetch consumption data của Integration vẫn hoạt động bình thường đối với EVNSPC không?

Mình có gửi mail cho bác rùi mà. Chứ năng login vẫn hoạt động bình thường. Nhưng do EVNSPC nó đổi cấu trúc nên mới lỗi không thể lấy fetch data đc. 
Bác check gmail rùi add zalo của mình, mình sẽ giải thích rõ hơn

**Comment by leolionart** [comment]
Update mới nhất ngon rồi. Cảm ơn bác bác @chautruongthinh và bác Huy
