### ISSUE TITLE
[EVNHCMC] Energy Dashboard - Entity Not Defined

### ISSUE THREAD

**Issue by Builder-DE-TH** [trvqhuy/nestup_evn#7]
**Mô tả lỗi / Describe the bug**
When I add the sensor to the Energy Dashboard it returns the error, Entity not defined"

**Logs**
No error in logs

**Ảnh chụp / Screenshots**

![end2](https://user-images.githubusercontent.com/109861242/191261471-c0aa737b-6518-4d81-b178-4625bde5ad1b.png)

**Server (thông tin máy chủ đang chạy HA):**
 - OS: Proxmox 7.1
 - HA platform: HAOS
 - HA Version: 2022.9.5

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: v.2.1.0

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by trvqhuy** [comment]
Hi @Builder-DE-TH, đó là thông tin của entity cũ từ phiên bản trước mà bạn chưa xóa.

Lỗi này xảy ra do bạn không gỡ thiết bị cũ hoàn toàn trước khi cài đặt EVN phiên bản mới nhất.

**Comment by Builder-DE-TH** [comment]
Thanks for this.

How do I make sure I have the old version deleted?

Where are the files that need to be deleted?

**Comment by trvqhuy** [comment]
Well, 

You can try adding a new sensor entity into the energy dashboard with the id `(your customer id here)_econ_total_new`.

Unfortunately, please pay attention that adding sensors into Energy dashboard is currently **not supported** for all regions in Vietnam, so the data might be messed up, or even not available.

This feature is in experimental process (with crossed fingers).

**Comment by Builder-DE-TH** [comment]
OK.

I tried adding the new sensor but that didn't work.
I deleted the old version incorrectly but I deleted 2.1.0 correctly and the new sensor (and old ones) are still showing up in the energy dashboard dropdowns.
I didn't know that the energy dashboard was experimental at the moment.
Will I open a feature request to remove them upon deleting?

**Comment by trvqhuy** [comment]
Sure @Builder-DE-TH, that would be great.
