### ISSUE TITLE
Error fetching khi update HA 2024.11.3

### ISSUE THREAD

**Issue by datvista** [trvqhuy/nestup_evn#71]
This error originated from a custom integration.

Logger: custom_components.nestup_evn.sensor
Source: helpers/update_coordinator.py:382
integration: EVN Data Fetcher (documentation, issues)
First occurred: 7:30:58 AM (1 occurrences)
Last logged: 7:30:58 AM

Unexpected error fetching nestup_evn-PE04000011867 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nestup_evn/sensor.py", line 123, in _async_update
    await self.update()
  File "/config/custom_components/nestup_evn/sensor.py", line 101, in update
    self._data = await self._api.request_update(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nestup_evn/nestup_evn.py", line 122, in request_update
    fetch_data = await self.request_update_evnhcmc(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nestup_evn/nestup_evn.py", line 481, in request_update_evnhcmc
    from_date = parser.parse(resp_json[0]["ngayFull"], dayfirst=True)
                             ~~~~~~~~~^^^
IndexError: list index out of range

**Logs**
Thêm phần logs báo lỗi của HA có liên quan đến Integration.

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.

**Server (thông tin máy chủ đang chạy HA):**
 - OS: [e.g. Linux]
 - HA platform: [e.g. Core]
 - HA Version: [e.g. 2022.7.0]

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [e.g. HACS] (cách cài đặt Integration)
 - Version: [e.g. v.2.1.0]

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by anhnvme** [comment]
.2 hôm nay cũng bị báo unavailable rồi!
[image](https://github.com/user-attachments/assets/95469d88-e53b-4aff-85a5-1cc235907534)

**Comment by trvqhuy** [comment]
Hi @datvista @anhnvme , cho mình hỏi đến hôm nay Integration đã hoạt động bình thường chưa nhỉ?

**Comment by anhnvme** [comment]
> Hi @datvista @anhnvme , cho mình hỏi đến hôm nay Integration đã hoạt động bình thường chưa nhỉ?

ok rồi bạn nhé

**Comment by datvista** [comment]
Đã hoạt động bình thường, cảm ơn bạn.
