### ISSUE TITLE
[HCMPC] cập nhật lên phiên bảm 2.4.5 - không có được thông tin đồng hồ

### ISSUE THREAD

**Issue by nhnam100** [trvqhuy/nestup_evn#78]
**Mô tả lỗi / Describe the bug**
Sau khi cập nhật phiên bản 2.4.5 thì chỉ  phát hiện ra 1 dồng hồ; không có dữ liệu;
Gỡ ra, cài đặt lại thì không thấy thiết bị nữa - thông tin cài đặt từ integration là 2.4.1 (xem hình)
mặc dù quá trình cài đặt trôi chảy

**Logs**
-

**Ảnh chụp / Screenshots**

![2024-12-17 10 05 33](https://github.com/user-attachments/assets/d53f9474-a059-4293-9404-c445b64d3ee6)

**Server (thông tin máy chủ đang chạy HA):**
 - OS: Linux Debian 11
 - HA platform: OrangePI 5, 8GB RAM; 128 M2 SSD
 - HA Version: 2024.12.0

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: 2.4.5

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by vdt2210** [comment]
> Bác inbox giúp mình tk nha. Mình coi lỗi gì rùi fix thử

Bug này fix chưa vậy bạn. Mình cũng đang bị như vậy @chautruongthinh

**Comment by chautruongthinh** [comment]
> Bug này fix chưa vậy bạn. Mình cũng đang bị như vậy @chautruongthinh

Mình vừa mới fix xong, đang test thử. Bác truy cập github của mình test thử nha

**Comment by vdt2210** [comment]
> > Bug này fix chưa vậy bạn. Mình cũng đang bị như vậy @chautruongthinh
> 
> Mình vừa mới fix xong, đang test thử. Bác truy cập github của mình test thử nha

hoạt động bth rồi bạn. hy vọng merge lên bản chính. à mà cái sản lượng hôm nay chưa thấy khi nào work v nhỉ

**Comment by chautruongthinh** [comment]
> hoạt động bth rồi bạn. hy vọng merge lên bản chính. à mà cái sản lượng hôm nay chưa thấy khi nào work v nhỉ
Sản lượng hôm qua và sản lượng hôm kia thui bác, sản lượng hôm nay sẽ không có

**Comment by trvqhuy** [comment]
Mình đã merge vào branch chính, mời các bạn sử dụng và đánh giá nhé.

Cảm ơn bạn @chautruongthinh vì những đóng góp này.
