### ISSUE TITLE
[EVNNPC] Data unavailable after few minutes

### ISSUE THREAD

**Issue by cuncon37** [trvqhuy/nestup_evn#8]
Mình đã thêm được vào HASS nhưng chỉ chạy được một chút lại bị lỗi 
![image](https://user-images.githubusercontent.com/48887234/191469612-51f86b6e-a20d-4c0c-86d5-7cbea42dd74c.png)
Mình vẫn đăng nhập được vào trang CSKH của EVN.
![image](https://user-images.githubusercontent.com/48887234/191469965-3426d31e-8bbb-4e64-8a9d-50488da96403.png)

Hệ thống HASS:
![image](https://user-images.githubusercontent.com/48887234/191469874-fc0ea005-f2a1-454f-a38d-45295086dba9.png)

**Comment by trvqhuy** [comment]
bạn chụp phần logs có liên quan giúp mình nhé
